/**:
  ros__parameters:
    x0: -0.5
    y0: 0.7
    theta0: 1.28
    rate: 200
    walls:
      arena_x_length: 6.0
      arena_y_length: 6.0
    obstacles:
      x: [-0.5, 0.8, 0.4]
      y: [-0.7, -0.8, 0.8]
      r: 0.038

